feat: 새로운 공통응답 클래스
team-suwiki/SUWIKI-Spring pull request #107
Opened 2024-07-07 14:27 UTC by wlsdlf2

## 🙋 어떤 PR인가요?

## 📝 작업 상세

## 🙏 To Reviewers

## 🧐 체크리스트

- [ ]  본인을 Assign해주시고, 본인을 제외한 백엔드 개발자를 Reviewer로 지정해주세요.
- [ ]  라벨 체크해주세요.
- [ ]  .yml 파일 수정 내용이 있다면 공유해주세요!
- [ ]  정상동작하는지, 테스트 통과하는지 다시 한번 확인해주세요.

2024-07-12 17:20 UTC, Hejow requested changes

2024-07-12 17:20 UTC, Hejow commented on usw-suwiki-common/src/main/java/usw/suwiki/common/response/CommonResponse.java
> +    public static CommonResponse<?> success() { return new CommonResponse<>(Map.of("success", true)); }
기본적으로 네이버 컨벤션을 사용하고 있기 때문에 한 라인은 어렵구
success에 대해서 Map으로 넘기지 말아보죠!

2024-07-16 05:33 UTC, wlsdlf2 commented on usw-suwiki-common/src/main/java/usw/suwiki/common/response/CommonResponse.java
> +    public static CommonResponse<?> success() { return new CommonResponse<>(Map.of("success", true)); }
넵

2024-07-23 08:58 UTC, Hejow approved these changes
하아 제가 너무 늦게봤네요 !! 고생하셨어요!

2024-08-05 00:33 UTC, Hejow approved these changes
우선 머지 때리시죵 ~ 고생하셨어요!!

2024-08-05 02:38 UTC, wlsdlf2 commented
저한테 merge버튼이 안떠서 희조님이 해주시면 감사하겠습니다~

2024-08-05 04:55 UTC, merged